baseURL = "https://marcopizzolato.com/"
DefaultContentLanguage = "en"
languageCode = 'en-us'
title = "Marco Pizzolato Portfolio"
theme = 'lightbi-hugo'
metaDataFormat = "yaml"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = true
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
authorInfo = "She was born to be free, let her run wild in her own way and you will never lose her."
description="Personal portfolio of Marco Pizzolato, Data Engineer and Geospatial Expert."
previewCardImagePlacement = "bottom"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Marco Pizzolato"
  website = "https://marcopizzolato.com/"
#  email = "sample@gmail.com"
  linkedin = "pizzolatomarco"
  github = "marcopizzolato-mp"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

#[[menu.main]]
#    name = "Notes"
#    url = "/notes/"
#    weight = 2
#
#[[menu.main]]
#    name = "Tags"
#    url = "/tags/blog/"
#    weight = 3
#
#[[menu.main]]
#    name = "Collections"
#    url = "/collections/"
#    weight = 4


