# Global settings for the Hugo site
[build]
publish = "public"
command = "git submodule update --init --recursive && hugo mod get -u && hugo --gc --minify"

# Default environment variables for all contexts unless overridden
[build.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# Production-specific settings
[context.production]

# Settings for a specific context named 'split1'
[context.split1]
command = "hugo --gc --minify --enableGitInfo"

# Deploy preview settings
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

# Branch-specific deploy settings
[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"
